apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
  labels:
    project: roboshop
    component: redis 
    env: dev 
spec:
  selector:
      project: roboshop
      component: redis 
      env: dev 
  clusterIP: None
  ports:
  - port: 27017  # service port
    targetPort: 27017  # container port     
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis 
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      component: redis
      env: dev 
      
  serviceName: "redis-headless"
  replicas: 1
  #minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        env: dev 
      
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis 
        image: subbukola541/redis:7.0
        volumeMounts:
        - name: redis 
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: redis 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "redis-ebs"
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    component: redis
    env: dev 
spec:
  selector:
      project: roboshop
      component: redis
      env: dev 
  
  ports:
  - port: 6379  # service port
    targetPort: 6379  # container port 